db: shop
server:
  port: 8080
  servlet:
    context-path: /shop/manager
    session:
      cookie:
        name: ROBOT_MANAGE_SID
    tomcat:
      max-connections: 10000
      max-http-form-post-size: 500MB
      max-swallow-size: 500MB
      max-threads: 1000
      min-spare-threads: 500
spring:
  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 5000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: druid,mybatisplus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${db}?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  rabbitmq:
    host: 117.78.10.200
    port: 42803
    username: admin
    password: 1qazxsw2
    publisher-returns: true
    virtual-host: /
    listener:
      simple:
        #        自动确认消费
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
  redis:
    #数据库索引
    database: 14
    host: 127.0.0.1
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000
logging:
  config: classpath:logback.xml
  level:
    com.hzxy.ciskyoneaxpe.mapper: debug
    com.hzxy.common.mapper: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

ScheduledCron:
  #定时器开关 true-开 false-关
  enabled: false

holiday_group_mq:
  #交换机名称
  holiday_exchange_name: holiday_exchange
